import { Booking, Review, Service, Shop, TimeSlot } from "./types";

export const SHOPS: Shop[] = [
  {
    id: "1",
    name: "Gentlemen's Den",
    image: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=600&q=80",
    rating: 4.8,
    reviewCount: 312,
    bookingCount: 186,
    distance: "0.8 km",
    startingPrice: 149,
    nextSlot: "2:30 PM",
    address: "12, MG Road, Koramangala, Bengaluru",
    category: "Premium",
    tags: ["AC", "Parking", "Wi-Fi"],
    about: "Award-winning barbershop delivering premium grooming experiences since 2016. Our expert barbers specialize in classic cuts, modern fades, and luxurious beard grooming.",
    openTime: "09:00 AM",
    closeTime: "09:00 PM",
  },
  {
    id: "2",
    name: "The Blade Studio",
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80",
    rating: 4.6,
    reviewCount: 218,
    bookingCount: 132,
    distance: "1.2 km",
    startingPrice: 199,
    nextSlot: "3:00 PM",
    address: "45, Indiranagar 100ft Road, Bengaluru",
    category: "Luxury",
    tags: ["AC", "Premium Products"],
    about: "A sanctuary for the modern gentleman. The Blade Studio combines old-school craftsmanship with contemporary styles.",
    openTime: "10:00 AM",
    closeTime: "10:00 PM",
  },
  {
    id: "3",
    name: "Royal Cuts",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    rating: 4.5,
    reviewCount: 187,
    bookingCount: 94,
    distance: "1.5 km",
    startingPrice: 99,
    nextSlot: "4:00 PM",
    address: "8, HSR Layout, Sector 6, Bengaluru",
    category: "Budget",
    tags: ["Walk-in", "AC"],
    about: "Affordable quality grooming for every budget. Walk-ins welcome, expert barbers, and consistently great results.",
    openTime: "08:00 AM",
    closeTime: "08:00 PM",
  },
  {
    id: "4",
    name: "Urban Barber Co.",
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80",
    rating: 4.7,
    reviewCount: 445,
    bookingCount: 248,
    distance: "2.1 km",
    startingPrice: 179,
    nextSlot: "5:30 PM",
    address: "33, Whitefield Main Road, Bengaluru",
    category: "Premium",
    tags: ["AC", "Wi-Fi", "Parking", "Card Accepted"],
    about: "Modern barbershop experience with state-of-the-art equipment and a team of internationally trained barbers.",
    openTime: "09:00 AM",
    closeTime: "09:30 PM",
  },
  {
    id: "5",
    name: "Classic Shave",
    image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=600&q=80",
    rating: 4.4,
    reviewCount: 156,
    bookingCount: 88,
    distance: "2.7 km",
    startingPrice: 129,
    nextSlot: "1:00 PM",
    address: "22, JP Nagar 7th Phase, Bengaluru",
    category: "Standard",
    tags: ["Walk-in", "AC"],
    about: "Bringing back the tradition of classic grooming. Hot towel shaves, precision cuts, and a relaxing atmosphere.",
    openTime: "09:30 AM",
    closeTime: "08:30 PM",
  },
  {
    id: "6",
    name: "StyleKraft Salon",
    image: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=600&q=80",
    rating: 4.9,
    reviewCount: 523,
    bookingCount: 281,
    distance: "3.4 km",
    startingPrice: 249,
    nextSlot: "6:00 PM",
    address: "7, Brigade Road, Shivajinagar, Bengaluru",
    category: "Luxury",
    tags: ["AC", "Premium", "Parking", "Wi-Fi"],
    about: "The pinnacle of grooming luxury in Bengaluru. StyleKraft combines artistry with science for an unparalleled salon experience.",
    openTime: "10:00 AM",
    closeTime: "10:30 PM",
  },
];

export const SERVICES: Service[] = [
  { id: "s1", name: "Haircut", icon: "Scissors", duration: "30 min", price: 149, popular: true },
  { id: "s2", name: "Beard Trim", icon: "Smile", duration: "20 min", price: 99 },
  { id: "s3", name: "Head Massage", icon: "Hand", duration: "30 min", price: 199 },
  { id: "s4", name: "Hair Color", icon: "Droplets", duration: "60 min", price: 499 },
  { id: "s5", name: "Face Spa", icon: "Sparkles", duration: "45 min", price: 349 },
  { id: "s6", name: "Haircut + Beard", icon: "Star", duration: "45 min", price: 229, popular: true },
  { id: "s7", name: "Shampoo & Style", icon: "Wind", duration: "30 min", price: 179 },
  { id: "s8", name: "Hot Towel Shave", icon: "Flame", duration: "25 min", price: 129 },
];

export const TIME_SLOTS_TODAY: TimeSlot[] = [
  { time: "9:00 AM", available: false },
  { time: "9:30 AM", available: false },
  { time: "10:00 AM", available: false },
  { time: "10:30 AM", available: true },
  { time: "11:00 AM", available: true },
  { time: "11:30 AM", available: false },
  { time: "12:00 PM", available: true },
  { time: "12:30 PM", available: false },
  { time: "1:00 PM", available: true },
  { time: "1:30 PM", available: true },
  { time: "2:00 PM", available: false },
  { time: "2:30 PM", available: true },
  { time: "3:00 PM", available: true },
  { time: "3:30 PM", available: true },
  { time: "4:00 PM", available: false },
  { time: "4:30 PM", available: true },
  { time: "5:00 PM", available: true },
  { time: "5:30 PM", available: false },
];

export const TIME_SLOTS_TOMORROW: TimeSlot[] = [
  { time: "9:00 AM", available: true },
  { time: "9:30 AM", available: true },
  { time: "10:00 AM", available: true },
  { time: "10:30 AM", available: false },
  { time: "11:00 AM", available: true },
  { time: "11:30 AM", available: true },
  { time: "12:00 PM", available: false },
  { time: "12:30 PM", available: true },
  { time: "1:00 PM", available: false },
  { time: "1:30 PM", available: true },
  { time: "2:00 PM", available: true },
  { time: "2:30 PM", available: false },
  { time: "3:00 PM", available: true },
  { time: "3:30 PM", available: true },
  { time: "4:00 PM", available: true },
  { time: "4:30 PM", available: false },
  { time: "5:00 PM", available: true },
  { time: "5:30 PM", available: true },
];

export const CATEGORIES = ["All", "Near Me", "Trending"];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    shopId: "1",
    userId: "user-1",
    shopName: "Gentlemen's Den",
    shopImage: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=600&q=80",
    service: "Haircut + Beard Trim",
    date: "Today",
    time: "3:30 PM",
    address: "12, MG Road, Koramangala",
    price: 248,
    status: "confirmed",
  },
  {
    id: "b2",
    shopId: "4",
    userId: "user-1",
    shopName: "Urban Barber Co.",
    shopImage: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80",
    service: "Haircut",
    date: "Fri, 21 Mar",
    time: "11:00 AM",
    address: "33, Whitefield Main Road",
    price: 179,
    status: "confirmed",
  },
  {
    id: "b3",
    shopId: "3",
    userId: "user-1",
    shopName: "Royal Cuts",
    shopImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    service: "Head Massage",
    date: "Mon, 15 Mar",
    time: "5:00 PM",
    address: "8, HSR Layout, Sector 6",
    price: 199,
    status: "completed",
  },
  {
    id: "b4",
    shopId: "2",
    userId: "user-1",
    shopName: "The Blade Studio",
    shopImage: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80",
    service: "Hair Color",
    date: "Sat, 8 Mar",
    time: "2:00 PM",
    address: "45, Indiranagar 100ft Road",
    price: 499,
    status: "cancelled",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    reviewId: "review-seed-1",
    userId: "Rahul M.",
    shopId: "1",
    rating: 5,
    reviewText: "Best haircut I have had in Bengaluru. The team is super professional.",
    tags: ["Clean", "Good Staff"],
    createdAt: "2026-03-17T10:00:00.000Z",
  },
  {
    reviewId: "review-seed-2",
    userId: "Arjun S.",
    shopId: "1",
    rating: 4,
    reviewText: "Great ambience and skilled barbers. A little premium, but worth it.",
    tags: ["Fast Service", "Clean"],
    createdAt: "2026-03-13T18:30:00.000Z",
  },
  {
    reviewId: "review-seed-3",
    userId: "Vikram P.",
    shopId: "4",
    rating: 5,
    reviewText: "Booked through TRIMO for the first time and the experience felt seamless.",
    tags: ["Good Staff", "Fast Service"],
    createdAt: "2026-03-08T09:45:00.000Z",
  },
  {
    reviewId: "review-seed-4",
    userId: "Sameer K.",
    shopId: "3",
    rating: 4,
    reviewText: "Affordable pricing, quick service, and the trim came out exactly right.",
    tags: ["Affordable", "Fast Service"],
    createdAt: "2026-03-05T12:20:00.000Z",
  },
];
